name: comic_reader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  archive: ^4.0.7
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.1.1
  file_picker: ^10.3.8
  firebase_ai: ^3.6.1
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_storage: ^13.0.5
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  go_router: ^17.0.1
  http: ^1.6.0
  image: ^4.7.2
  path: ^1.9.1
  rar: ^0.3.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
